server:
  port: 9090

#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      auto-offset-reset: earliest
#    producer:
#      bootstrap-servers: localhost:9092
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#kafka:
#  topic:
#    my-topic: my-topic
#    my-topic2: my-topic2